apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-basedeployment
  namespace: {{ NAMESPACE }}
  labels:
    app: oncallservices
spec:
  selector:
    matchLabels:
      app: oncallservices
  replicas: 1
  template:
    metadata:
      labels:
        app: oncallservices
    spec:
      containers:
      - name: oncallservices
        image: {{ image.tag }}
        args: ["--spring.profiles.active={{ENVIRONMENT}}"]
        ports:
          - containerPort: {{ SERVICEPORT }}
        volumeMounts:
          - name: oncall-config-volume
            mountPath: /opt/oncall/
      volumes:
        - name: oncall-config-volume
          configMap:
            defaultMode: 420
            name: oncall-server-conf
        livenessProbe:
          httpGet:
            path: /test
            port: {{ SERVICEPORT }}
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "1Gi"
            cpu: "400m"
          limits:
            memory: "2Gi"
            cpu: "800m"
