apiVersion: v1
kind: Service
metadata:
  labels:
    app: oncallservices
  name: oncallservices
  namespace: {{ NAMESPACE }}
spec:
  ports:
    - name: oncall
      port: {{ SERVICEPORT }}
      protocol: TCP
  selector:
    app: oncallservices
